name: Delete Terraform Workspace
on:
  push:
    branches:
      - workspace

jobs:
  runterraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List out directory
        run: ls

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init -upgrade

      - name: Terraform list workspaces
        run: terraform workspace list

      - name: Terraform delete workspace
        run: terraform workspace delete terraform-sandeep-aws -force



